// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCLRrqDwCOff4UIVP2otMFzwMtr_jz67U',
    appId: '1:47234500199:web:623000bc86ce0e9142f6c2',
    messagingSenderId: '47234500199',
    projectId: 'snapkhata',
    authDomain: 'snapkhata.firebaseapp.com',
    storageBucket: 'snapkhata.firebasestorage.app',
    measurementId: 'G-GW4E3BVNXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDCQWdcRn0e2R0azqIVhg8d14d59Dd468',
    appId: '1:47234500199:android:75de60efade553da42f6c2',
    messagingSenderId: '47234500199',
    projectId: 'snapkhata',
    storageBucket: 'snapkhata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFFMXMcdaA9i06nRSysG_Wmc9OONcKJIs',
    appId: '1:47234500199:ios:070ac54b7cb2abf742f6c2',
    messagingSenderId: '47234500199',
    projectId: 'snapkhata',
    storageBucket: 'snapkhata.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
}
